### ISSUE TITLE
Testing ompi label bot -- please ignore

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi-release#205]
label:bug
milestone:v1.8.5
assign:@jsquyres

**Comment by jsquyres** [comment]
bot:label:bug
bot:milestone:v1.8.5
bot:assign:@jsquyres

**Comment by jsquyres** [comment]
@ggouaillardet Somehow the labels cache file is empty:

```
% ls -l /tmp/ompi-release-label-bot-labels.json 
-rw-r--r--. 1 apache apache 0 Mar  5 21:37 /tmp/ompi-release-label-bot-labels.json
```

How can that happen?

The index.php that I am using is from the current HEAD: open-mpi/ompi-release-bot@2ba0b699328d1a2587ef91c5c33e1e0e3f73efd6

**Comment by ggouaillardet** [comment]
fixed in open-mpi/ompi-bot-release@87a40b43d0bf261af0de9ef592082ef9b5cc50de

there was one typo ($files instead of $file) and an incorrect syntax ...
```
$fd = fopen($file, "w") || die("could not open $file\n");
```
is not what's needed (that makes $fd a boolean, and following fwrite/fclose will fail)

```
$fd = fopen($file, "w") or die("could not open $file\n");
```
does what is expected here

**Comment by jsquyres** [comment]
bot:milestone:v1.8.5
bot:label:enhancement

**Comment by jsquyres** [comment]
Ok, the file is now non-empty, but milestones still don't work.  Here's the label file:

```json
{"ETag":"531bbe9b3585e8e7f41ba69c62515bb2","bug":"L","duplicate":"L","enhancement":
"L","invalid":"L","wontfix":"L","reviewed":"L","blocker":"L","pushed-back":"L","doc
umentation":"L","RM-Approved":"L","Conditional-Approval":"L","Code-cleanup-low-prio
rity":"L"}
```

I am about to board a plane; I might be able to look at the code (much) later today...?

**Comment by jsquyres** [comment]
Hmm.  One thing I notice immediately is that there are no milestones in that JSON -- only labels...

**Comment by jsquyres** [comment]
bot:milestone:v1.8.5

**Comment by jsquyres** [comment]
Huh.  Now it worked (I didn't make any change to the code).  What the heck.

**Comment by jsquyres** [comment]
And now there's a new cache file for the milestones:

```
 % more /tmp/ompi-release-label-bot-milestones.json 
{"ETag":null,"v1.9.0":3,"v1.9.1":4,"v1.8.5":2}
```

**Comment by jsquyres** [comment]
bot:milestone:v1.9.0

**Comment by jsquyres** [comment]
bot:milestone:v1.8.5

**Comment by jsquyres** [comment]
@ggouaillardet Now I'm really confused. :-( Why did bot:milestone work here just moments ago, but it failed a few hours ago when @rolfv tried to assign v1.8.5 on #206?

**Comment by goodell** [comment]
I blame PHP. :wink:

**Comment by jsquyres** [comment]
bot:nomilestone

**Comment by jsquyres** [comment]
bot:label:invalid

**Comment by jsquyres** [comment]
bot:milestone:v1.10 hello

**Comment by jsquyres** [comment]
bot:milestone:v1.10 hello

**Comment by jsquyres** [comment]
bot:milestone:v1.10

**Comment by jsquyres** [comment]
bit:milestone:v1.10 hello

**Comment by jsquyres** [comment]
bot:milestone:v1.10 hello

**Comment by jsquyres** [comment]
It helps when the milestone actually exists :-) (it was "1.10", not "v1.10")

**Comment by jsquyres** [comment]
Let's put something before the command bot:milestone:v1.8.6 and something after the command

**Comment by jsquyres** [comment]
...actually, we should keep with our new versioning rules: it's v1.10.0 now (i.e., always include the 3rd number).
